In [1]:
import tensorflow_hub as hub

use_model = hub.load(
    "https://tfhub.dev/google/universal-sentence-encoder/4"
)

print("Universal Sentence Encoder loaded!")

d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tensorflow_hub\__init__.py:61: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

WARNING:tensorflow:From d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tensorflow_hub\module_v2.py:126: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

WARNING:tensorflow:From d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tensorflow_hub\module_v2.py:126: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

Universal Sentence Encoder loaded!

In [3]:
from huggingface_hub import hf_hub_download
from pathlib import Path
import pandas as pd

# Your project
project_dir = Path(r"D:\rock-n-roll-discover-server")
data_dir = project_dir / "data"
data_dir.mkdir(exist_ok=True)

# Download dataset
parquet_path = hf_hub_download(
    repo_id="lang-uk/recruitment-dataset-job-descriptions-english",
    filename="data/train-00000-of-00001.parquet",
    repo_type="dataset"
)

# Read Parquet
df = pd.read_parquet(parquet_path)

# Save as CSV inside your project
csv_path = data_dir / "jobs.csv"
df.to_csv(csv_path, index=False)

print("CSV saved successfully!")
print("Location:", csv_path)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

d:\rock-n-roll-discover-server\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

CSV saved successfully!
Location: D:\rock-n-roll-discover-server\data\jobs.csv
Shape: (141897, 10)
Columns: ['Position', 'Long Description', 'Company Name', 'Exp Years', 'Primary Keyword', 'English Level', 'Published', 'Long Description_lang', 'id', '__index_level_0__']

In [4]:
from huggingface_hub import hf_hub_download
from pathlib import Path
import pandas as pd

# Your project
project_dir = Path(r"D:\rock-n-roll-discover-server")
data_dir = project_dir / "data"
data_dir.mkdir(exist_ok=True)

# Download candidate dataset
path = hf_hub_download(
    repo_id="pylover/recruitment-dataset-candidate-profiles-english",
    filename="data/train-00000-of-00001.parquet",
    repo_type="dataset"
)

print("Downloaded:", path)

# Read dataset
df_candidates = pd.read_parquet(path)

# Save as CSV inside your project
csv_path = data_dir / "candidates.csv"
df_candidates.to_csv(csv_path, index=False)

print("CSV saved successfully!")
print("Location:", csv_path)
print("Shape:", df_candidates.shape)
print("Columns:", df_candidates.columns.tolist())

Downloaded: C:\Users\HP\.cache\huggingface\hub\datasets--pylover--recruitment-dataset-candidate-profiles-english\snapshots\b06203875fde6a0c95039deef71ac50b976ed812\data\train-00000-of-00001.parquet
CSV saved successfully!
Location: D:\rock-n-roll-discover-server\data\candidates.csv
Shape: (210250, 11)
Columns: ['Position', 'Moreinfo', 'Looking For', 'Highlights', 'Primary Keyword', 'English Level', 'Experience Years', 'CV', 'CV_lang', 'id', '__index_level_0__']

In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import pandas as pd

df_jobs = pd.read_csv(
    r"D:\rock-n-roll-discover-server\data\jobs.csv"
)

print(df_jobs.shape)
print(df_jobs.columns.tolist())

(141897, 10)
['Position', 'Long Description', 'Company Name', 'Exp Years', 'Primary Keyword', 'English Level', 'Published', 'Long Description_lang', 'id', '__index_level_0__']

In [6]:
import pandas as pd

path = r"D:\rock-n-roll-discover-server\data\jobs.csv"

df_jobs = pd.read_csv(path)

print("Shape:", df_jobs.shape)
print("\nColumns:")
print(df_jobs.columns.tolist())

print("\nMissing values:")
print(df_jobs.isna().sum())

print("\nFirst 5 rows:")
display(df_jobs.head())

Shape: (141897, 10)

Columns:
['Position', 'Long Description', 'Company Name', 'Exp Years', 'Primary Keyword', 'English Level', 'Published', 'Long Description_lang', 'id', '__index_level_0__']

Missing values:
Position                    0
Long Description            0
Company Name                0
Exp Years                   0
Primary Keyword             0
English Level            7539
Published                   0
Long Description_lang       0
id                          0
__index_level_0__           0
dtype: int64

First 5 rows:

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,Long Description_lang,id,__index_level_0__
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...,MyCointainer,2y,Sysadmin,intermediate,2020-10-01T00:00:00+03:00,en,c0ca96e7-85df-50df-a64e-d934cd02a170,27461
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne...",TechScout.tech,2y,.NET,intermediate,2022-03-01T00:00:00+02:00,en,64f4b7ea-36e4-5bdd-a8b1-185f32f7dc7f,27462
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...,Innoteka,5y,JavaScript,fluent,2021-07-01T00:00:00+03:00,en,b9a1303e-dd0c-5ed1-8f62-be2bc4c7da4f,27463
3,16 - Amazon Brand Manager,"Currently, TCM expanding its activities to Ukr...",FirstFive,2y,Marketing,upper,2022-01-01T00:00:00+02:00,en,99cb3f4a-9b4b-53d9-9a3b-bab2c22da346,27464
4,16 - Amazon Brand Manager,"Hello,\r\nWe, MIMIRB2B, are an outstaff compan...",MimirB2B,1y,Marketing,upper,2021-12-01T00:00:00+02:00,en,bc1419f7-28e2-582b-8d53-22e28b2f0210,27465

In [11]:
import pandas as pd

jobs = pd.read_csv(r"D:\rock-n-roll-discover-server\data\jobs.csv")
candidates = pd.read_csv(r"D:\rock-n-roll-discover-server\data\candidates.csv")

print("===== JOBS =====")
print(jobs.shape)
print(jobs.columns.tolist())
display(jobs.head(3))

print("\n===== CANDIDATES =====")
print(candidates.shape)
print(candidates.columns.tolist())
display(candidates.head(3))

===== JOBS =====
(141897, 10)
['Position', 'Long Description', 'Company Name', 'Exp Years', 'Primary Keyword', 'English Level', 'Published', 'Long Description_lang', 'id', '__index_level_0__']

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,Long Description_lang,id,__index_level_0__
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...,MyCointainer,2y,Sysadmin,intermediate,2020-10-01T00:00:00+03:00,en,c0ca96e7-85df-50df-a64e-d934cd02a170,27461
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne...",TechScout.tech,2y,.NET,intermediate,2022-03-01T00:00:00+02:00,en,64f4b7ea-36e4-5bdd-a8b1-185f32f7dc7f,27462
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...,Innoteka,5y,JavaScript,fluent,2021-07-01T00:00:00+03:00,en,b9a1303e-dd0c-5ed1-8f62-be2bc4c7da4f,27463

===== CANDIDATES =====
(210250, 11)
['Position', 'Moreinfo', 'Looking For', 'Highlights', 'Primary Keyword', 'English Level', 'Experience Years', 'CV', 'CV_lang', 'id', '__index_level_0__']

,Position,Moreinfo,Looking For,Highlights,Primary Keyword,English Level,Experience Years,CV,CV_lang,id,__index_level_0__
0,"13 years of exp || Solidity, C#, JavaScript ||...",Who am I:\r\n- 13 years of commercial experien...,I am interested in:\r\n- part-time engagement;...,Landed a role of Director of Blockchain Develo...,Lead,fluent,11.0,Landed a role of Director of Blockchain Develo...,en,50534b61-6826-52b1-9ac5-bfd2cfa348ec,24230
1,1c Developer,Worked on a mobile application for tracking trips,NaN,NaN,Other,intermediate,3.0,\nWorked on a mobile application for tracking ...,en,c2b9ea56-b5c8-50ec-a63b-053a5c8ff467,24231
2,1C developer,1 am an 1C developer. I deployed an 1C to typo...,NaN,NaN,Flutter,intermediate,11.0,\n1 am an 1C developer. I deployed an 1C to ty...,en,b3bfe3ed-ec25-56b2-8aaa-8c629120538e,24232

In [7]:
import pandas as pd
import numpy as np
import re

JOBS_PATH = r"D:\rock-n-roll-discover-server\data\jobs.csv"
CANDIDATES_PATH = r"D:\rock-n-roll-discover-server\data\candidates.csv"

jobs = pd.read_csv(JOBS_PATH)
candidates = pd.read_csv(CANDIDATES_PATH)

print("Jobs:", jobs.shape)
print("Candidates:", candidates.shape)

Jobs: (141897, 10)
Candidates: (210250, 11)

In [8]:
def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Remove markdown
    text = re.sub(r"\*\*", "", text)
    text = re.sub(r"#+", " ", text)

    # Remove URLs
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [9]:
def build_job_text(row):
    return (
        f"Job Title: {row['Position']}. "
        f"Primary Skill: {row['Primary Keyword']}. "
        f"Experience Required: {row['Exp Years']}. "
        f"English Level: {row['English Level']}. "
        f"Job Description: {row['Long Description']}"
    )

In [10]:
def normalize_skill(x):
    x = str(x).lower().strip()

    x = re.sub(r"[^a-z0-9+#.\- ]", " ", x)
    x = re.sub(r"\s+", " ", x)

    return x

In [11]:
def parse_experience(value):
    try:
        return float(value)
    except:
        return 0.0

In [12]:
# STEP 5 — Normalize Primary Keyword / Skill

import re

def normalize_skill(value):
    # Handle missing values
    if pd.isna(value):
        return ""

    # Convert to string and lowercase
    value = str(value).lower().strip()

    # Normalize common variations
    value = value.replace("&", "and")

    # Remove unwanted characters
    value = re.sub(r"[^a-z0-9+#.\- ]", " ", value)

    # Remove extra spaces
    value = re.sub(r"\s+", " ", value)

    return value.strip()


# Apply to jobs
jobs["skill"] = jobs["Primary Keyword"].apply(normalize_skill)

# Apply to candidates
candidates["skill"] = candidates["Primary Keyword"].apply(normalize_skill)


# Check results
print("Top Job Skills:")
print(jobs["skill"].value_counts().head(30))

print("\nTop Candidate Skills:")
print(candidates["skill"].value_counts().head(30))

Top Job Skills:
skill
javascript          17903
java                 8712
devops               7979
.net                 7826
other                7536
qa automation        7047
marketing            6933
qa                   6774
node.js              6416
php                  5740
python               5735
project manager      4618
hr                   4063
design               4020
sales                4014
c++                  3743
business analyst     3679
support              2819
android              2651
ios                  2398
data science         2262
product manager      1939
lead                 1861
ruby                 1834
golang               1747
sysadmin             1694
sql                  1459
data engineer        1451
unity                1165
lead generation       840
Name: count, dtype: int64

Top Candidate Skills:
skill
javascript          33980
qa                  25089
design              15068
project manager     12499
java                11463
.net                 9388
marketing            8984
python               7588
php                  6947
qa automation        5756
other                5395
node.js              4896
recruiter            4865
hr                   4776
support              4597
business analyst     4431
devops               4120
product manager      4048
sales                3784
ios                  3200
android              3087
c++                  2981
data science         2571
artist               2542
lead                 2373
data analyst         2271
unity                1815
sysadmin             1528
ruby                 1380
golang               1343
Name: count, dtype: int64

In [13]:
print("\nMissing job skills:")
print((jobs["skill"] == "").sum())

print("\nMissing candidate skills:")
print((candidates["skill"] == "").sum())

Missing job skills:
0

Missing candidate skills:
43

In [14]:
# STEP 6 — Generate positive job-candidate pairs

import numpy as np
import pandas as pd
from collections import defaultdict

# Random generator for reproducibility
rng = np.random.default_rng(42)

# ---------------------------------------------------------
# 1. Create an index of candidates grouped by skill
# ---------------------------------------------------------

candidate_by_skill = defaultdict(list)

for idx, skill in candidates["skill"].items():
    if skill != "":
        candidate_by_skill[skill].append(idx)

print("Number of skill groups:", len(candidate_by_skill))


# ---------------------------------------------------------
# 2. Generate positive pairs
# ---------------------------------------------------------

positive_pairs = []

MAX_POSITIVE_PAIRS = 100_000
CANDIDATES_PER_JOB = 3

for job_idx, job in jobs.iterrows():

    skill = job["skill"]

    # Find candidates with the same primary skill
    candidate_pool = candidate_by_skill.get(skill, [])

    if len(candidate_pool) == 0:
        continue

    # Select up to 3 candidates
    sample_size = min(
        CANDIDATES_PER_JOB,
        len(candidate_pool)
    )

    selected_candidates = rng.choice(
        candidate_pool,
        size=sample_size,
        replace=False
    )

    for candidate_idx in selected_candidates:

        positive_pairs.append({
            "job_idx": job_idx,
            "candidate_idx": candidate_idx,
            "label": 1
        })

    # Stop once we have enough
    if len(positive_pairs) >= MAX_POSITIVE_PAIRS:
        break


positive_pairs = pd.DataFrame(positive_pairs)

print("\nPositive pairs:", len(positive_pairs))
print(positive_pairs.head())

Number of skill groups: 41

Positive pairs: 100002
   job_idx  candidate_idx  label
0        0         187388      1
1        0          65195      1
2        0         187648      1
3        1          48621      1
4        1         170903      1

In [15]:
# STEP 7 — Generate negative job-candidate pairs

negative_pairs = []

MAX_NEGATIVE_PAIRS = 100_000
CANDIDATES_PER_JOB = 3

# Convert candidate indices to numpy array for faster sampling
all_candidate_indices = candidates.index.to_numpy()

for job_idx, job in jobs.iterrows():

    job_skill = job["skill"]

    # Candidates whose primary skill is DIFFERENT
    different_skill_candidates = candidates.index[
        candidates["skill"] != job_skill
    ].to_numpy()

    if len(different_skill_candidates) == 0:
        continue

    # Select up to 3 negative candidates
    sample_size = min(
        CANDIDATES_PER_JOB,
        len(different_skill_candidates)
    )

    selected_candidates = rng.choice(
        different_skill_candidates,
        size=sample_size,
        replace=False
    )

    for candidate_idx in selected_candidates:

        negative_pairs.append({
            "job_idx": job_idx,
            "candidate_idx": candidate_idx,
            "label": 0
        })

    if len(negative_pairs) >= MAX_NEGATIVE_PAIRS:
        break


negative_pairs = pd.DataFrame(negative_pairs)

print("Negative pairs:", len(negative_pairs))
print("\nSample:")
print(negative_pairs.head())

Negative pairs: 100002

Sample:
   job_idx  candidate_idx  label
0        0         183659      0
1        0         140770      0
2        0            383      0
3        1         100381      0
4        1         122850      0

In [16]:
# Recreate the combined pairs dataframe

pairs = pd.concat(
    [positive_pairs, negative_pairs],
    ignore_index=True
)

pairs = pairs.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Total pairs:", len(pairs))
print("\nLabels:")
print(pairs["label"].value_counts())

Total pairs: 200004

Labels:
label
0    100002
1    100002
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

# Get unique jobs
unique_jobs = pairs["job_idx"].unique()

print("Unique jobs:", len(unique_jobs))

# 80% train, 20% temporary
train_jobs, temp_jobs = train_test_split(
    unique_jobs,
    test_size=0.20,
    random_state=42
)

# Split remaining 20% into 10% validation + 10% test
val_jobs, test_jobs = train_test_split(
    temp_jobs,
    test_size=0.50,
    random_state=42
)

print("Train jobs:", len(train_jobs))
print("Validation jobs:", len(val_jobs))
print("Test jobs:", len(test_jobs))

Unique jobs: 33335
Train jobs: 26668
Validation jobs: 3333
Test jobs: 3334

In [18]:
train_pairs = pairs[
    pairs["job_idx"].isin(train_jobs)
].copy()

val_pairs = pairs[
    pairs["job_idx"].isin(val_jobs)
].copy()

test_pairs = pairs[
    pairs["job_idx"].isin(test_jobs)
].copy()

print("\nPair counts:")
print("Train:", len(train_pairs))
print("Validation:", len(val_pairs))
print("Test:", len(test_pairs))

Pair counts:
Train: 160005
Validation: 19995
Test: 20004

In [19]:
train_set = set(train_pairs["job_idx"])
val_set = set(val_pairs["job_idx"])
test_set = set(test_pairs["job_idx"])

print("\nLeakage checks:")
print("Train ∩ Validation:", len(train_set & val_set))
print("Train ∩ Test:", len(train_set & test_set))
print("Validation ∩ Test:", len(val_set & test_set))

Leakage checks:
Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [20]:
import os

data_dir = r"D:\rock-n-roll-discover-server\data"

train_pairs.to_csv(
    os.path.join(data_dir, "train_pairs.csv"),
    index=False
)

val_pairs.to_csv(
    os.path.join(data_dir, "val_pairs.csv"),
    index=False
)

test_pairs.to_csv(
    os.path.join(data_dir, "test_pairs.csv"),
    index=False
)

print("Saved successfully!")

Saved successfully!

In [21]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub
from tqdm.auto import tqdm

# Correct project paths
data_dir = r"D:\rock-n-roll-discover-server\data"

# Load datasets
jobs = pd.read_csv(os.path.join(data_dir, "jobs.csv"))
candidates = pd.read_csv(os.path.join(data_dir, "candidates.csv"))

print("Jobs:", jobs.shape)
print("Candidates:", candidates.shape)

# Load Universal Sentence Encoder
use_model = hub.load(
    "https://tfhub.dev/google/universal-sentence-encoder/4"
)

print("USE loaded successfully!")

Jobs: (141897, 10)
Candidates: (210250, 11)
USE loaded successfully!

In [22]:
EMBEDDING_BATCH_SIZE = 256

def generate_embeddings(texts, batch_size=256):
    embeddings = []

    for start in tqdm(
        range(0, len(texts), batch_size),
        desc="Generating embeddings"
    ):
        batch = texts[start:start + batch_size]

        vectors = use_model(batch).numpy()

        embeddings.append(vectors)

    return np.vstack(embeddings).astype("float32")

In [24]:
import re
import pandas as pd
import os

data_dir = r"D:\rock-n-roll-discover-server\data"

jobs = pd.read_csv(os.path.join(data_dir, "jobs.csv"))
candidates = pd.read_csv(os.path.join(data_dir, "candidates.csv"))

def clean_text(value):
    if pd.isna(value):
        return ""
    value = str(value)
    value = re.sub(r"\s+", " ", value)
    return value.strip()

# Build job text
jobs["job_text"] = (
    jobs["Position"].fillna("").apply(clean_text)
    + " "
    + jobs["Long Description"].fillna("").apply(clean_text)
    + " "
    + jobs["Primary Keyword"].fillna("").apply(clean_text)
)

# Build candidate text
candidates["candidate_text"] = (
    candidates["Position"].fillna("").apply(clean_text)
    + " "
    + candidates["Moreinfo"].fillna("").apply(clean_text)
    + " "
    + candidates["Looking For"].fillna("").apply(clean_text)
    + " "
    + candidates["Highlights"].fillna("").apply(clean_text)
    + " "
    + candidates["CV"].fillna("").apply(clean_text)
    + " "
    + candidates["Primary Keyword"].fillna("").apply(clean_text)
)

print("Job text created:", jobs["job_text"].notna().sum())
print("Candidate text created:", candidates["candidate_text"].notna().sum())

print("\nExample job:")
print(jobs["job_text"].iloc[0][:500])

print("\nExample candidate:")
print(candidates["candidate_text"].iloc[0][:500])

Job text created: 141897
Candidate text created: 210250

Example job:
10 + Blockchain Nodes / Masternodes to set up *Requirements* We're looking for a long term collaboration with someone that has an experience in crypto, masternodes, nodes, validators etc. We need to set up: Kyber Network Nebulas SecretNetwork Tron Aion DeFiChain EOS TomoChain Elrond IRISnet IoTeX Terra ChainX Thorchain Succesful candidates will have an opportunity to get more jobs and long term collaboration. Sysadmin

Example candidate:
13 years of exp || Solidity, C#, JavaScript || CTO / VP / Tech Lead Full stack Who am I: - 13 years of commercial experience as a software engineer (web projects, customers from Europe and US); - 5 years in roles of team lead, tech lead, architect (including coding); - constant learner (books, courses, youtube); - C1 (Advanced) level of English (IELTS General = 7/9); - tech languages: C#, JavaScript, Solidity; - ready to learn Rust/Go. What can I bring in: - develop your web/blockchain project f

In [25]:
print("job_text" in jobs.columns)
print("candidate_text" in candidates.columns)

True
True

In [26]:

job_texts = jobs["job_text"].fillna("").astype(str).tolist()

job_embeddings = generate_embeddings(
    job_texts,
    batch_size=256
)

print("Job embeddings shape:", job_embeddings.shape)

Generating embeddings: 100%|██████████| 555/555 [01:11<00:00,  7.76it/s]

Job embeddings shape: (141897, 512)

In [ ]:
job_embedding_path = os.path.join(
    data_dir,
    "job_embeddings.npy"
)

np.save(job_embedding_path, job_embeddings)

print("Saved:", job_embedding_path)

Saved: D:\rock-n-roll-discover-server\data\job_embeddings.npy

In [28]:
candidate_texts = (
    candidates["candidate_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

candidate_embeddings = generate_embeddings(
    candidate_texts,
    batch_size=256
)

print("Candidate embeddings shape:", candidate_embeddings.shape)

Generating embeddings: 100%|██████████| 822/822 [02:01<00:00,  6.77it/s]

Candidate embeddings shape: (210250, 512)

In [29]:
candidate_embedding_path = os.path.join(
    data_dir,
    "candidate_embeddings.npy"
)

np.save(
    candidate_embedding_path,
    candidate_embeddings
)

print("Saved:", candidate_embedding_path)

Saved: D:\rock-n-roll-discover-server\data\candidate_embeddings.npy

In [30]:
import numpy as np
import pandas as pd
import os

data_dir = r"D:\rock-n-roll-discover-server\data"

train_pairs = pd.read_csv(os.path.join(data_dir, "train_pairs.csv"))
val_pairs = pd.read_csv(os.path.join(data_dir, "val_pairs.csv"))
test_pairs = pd.read_csv(os.path.join(data_dir, "test_pairs.csv"))

job_embeddings = np.load(
    os.path.join(data_dir, "job_embeddings.npy")
)

candidate_embeddings = np.load(
    os.path.join(data_dir, "candidate_embeddings.npy")
)

print("Train pairs:", train_pairs.shape)
print("Validation pairs:", val_pairs.shape)
print("Test pairs:", test_pairs.shape)

print("Job embeddings:", job_embeddings.shape)
print("Candidate embeddings:", candidate_embeddings.shape)

print("\nIndex ranges:")
print("Job index:", train_pairs["job_idx"].min(), "→", train_pairs["job_idx"].max())
print("Candidate index:", train_pairs["candidate_idx"].min(), "→", train_pairs["candidate_idx"].max())

print("\nLabels:")
print(train_pairs["label"].value_counts())

Train pairs: (160005, 3)
Validation pairs: (19995, 3)
Test pairs: (20004, 3)
Job embeddings: (141897, 512)
Candidate embeddings: (210250, 512)

Index ranges:
Job index: 0 → 33334
Candidate index: 0 → 210249

Labels:
label
1    80004
0    80001
Name: count, dtype: int64

In [31]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# ============================================================
# PATHS
# ============================================================

data_dir = r"D:\rock-n-roll-discover-server\data"
model_dir = r"D:\rock-n-roll-discover-server\models"

os.makedirs(model_dir, exist_ok=True)

# ============================================================
# LOAD DATA
# ============================================================

train_pairs = pd.read_csv(
    os.path.join(data_dir, "train_pairs.csv")
)

val_pairs = pd.read_csv(
    os.path.join(data_dir, "val_pairs.csv")
)

test_pairs = pd.read_csv(
    os.path.join(data_dir, "test_pairs.csv")
)

job_embeddings = np.load(
    os.path.join(data_dir, "job_embeddings.npy")
)

candidate_embeddings = np.load(
    os.path.join(data_dir, "candidate_embeddings.npy")
)

print("Loaded successfully!")

print("Jobs:", job_embeddings.shape)
print("Candidates:", candidate_embeddings.shape)
print("Train:", train_pairs.shape)
print("Validation:", val_pairs.shape)
print("Test:", test_pairs.shape)

Loaded successfully!
Jobs: (141897, 512)
Candidates: (210250, 512)
Train: (160005, 3)
Validation: (19995, 3)
Test: (20004, 3)

In [33]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

EMBEDDING_DIM = 512
TOWER_DIM = 256


def build_tower(name):
    inputs = keras.Input(
        shape=(EMBEDDING_DIM,),
        name=f"{name}_input"
    )

    x = layers.Dense(
        512,
        activation="relu"
    )(inputs)

    x = layers.Dropout(0.1)(x)

    x = layers.Dense(
        TOWER_DIM
    )(x)

    # Keras 3 compatible L2 normalization
    outputs = layers.UnitNormalization(
        axis=1,
        name=f"{name}_normalize"
    )(x)

    return keras.Model(
        inputs=inputs,
        outputs=outputs,
        name=name
    )


job_tower = build_tower("job_tower")
candidate_tower = build_tower("candidate_tower")

job_tower.summary()
candidate_tower.summary()

Model: "job_tower"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ job_tower_input (InputLayer)    │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ job_tower_normalize             │ (None, 256)            │             0 │
│ (UnitNormalization)             │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 393,984 (1.50 MB)

 Trainable params: 393,984 (1.50 MB)

 Non-trainable params: 0 (0.00 B)

Model: "candidate_tower"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ candidate_tower_input           │ (None, 512)            │             0 │
│ (InputLayer)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ candidate_tower_normalize       │ (None, 256)            │             0 │
│ (UnitNormalization)             │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 393,984 (1.50 MB)

 Trainable params: 393,984 (1.50 MB)

 Non-trainable params: 0 (0.00 B)

In [34]:
class TwoTowerModel(keras.Model):

    def __init__(self, job_tower, candidate_tower):
        super().__init__()

        self.job_tower = job_tower
        self.candidate_tower = candidate_tower

        self.log_temperature = self.add_weight(
            name="log_temperature",
            shape=(),
            initializer=keras.initializers.Constant(
                np.log(0.07)
            ),
            trainable=True
        )

    def call(self, inputs):
        job_vectors, candidate_vectors = inputs

        job_output = self.job_tower(job_vectors)
        candidate_output = self.candidate_tower(
            candidate_vectors
        )

        temperature = tf.exp(
            self.log_temperature
        )

        similarity = tf.reduce_sum(
            job_output * candidate_output,
            axis=1
        )

        return similarity / temperature

In [35]:
model = TwoTowerModel(
    job_tower,
    candidate_tower
)

print("Two-Tower model created successfully!")

Two-Tower model created successfully!

In [36]:
import pandas as pd
import numpy as np

train_pairs = pd.read_csv("data/train_pairs.csv")
val_pairs = pd.read_csv("data/val_pairs.csv")
test_pairs = pd.read_csv("data/test_pairs.csv")

print("Train:", train_pairs.shape)
print("Validation:", val_pairs.shape)
print("Test:", test_pairs.shape)

print("\nTrain labels:")
print(train_pairs["label"].value_counts())

Train: (160005, 3)
Validation: (19995, 3)
Test: (20004, 3)

Train labels:
label
1    80004
0    80001
Name: count, dtype: int64

In [37]:
job_embeddings = np.load("data/job_embeddings.npy")
candidate_embeddings = np.load("data/candidate_embeddings.npy")

print("Job embeddings:", job_embeddings.shape)
print("Candidate embeddings:", candidate_embeddings.shape)

Job embeddings: (141897, 512)
Candidate embeddings: (210250, 512)

In [38]:
print("Maximum train job index:", train_pairs["job_idx"].max())
print("Maximum train candidate index:", train_pairs["candidate_idx"].max())

assert train_pairs["job_idx"].max() < len(job_embeddings)
assert train_pairs["candidate_idx"].max() < len(candidate_embeddings)

print("Index validation passed!")

Maximum train job index: 33334
Maximum train candidate index: 210249
Index validation passed!

In [40]:
# Keep only positive pairs
train_positive = train_pairs[train_pairs["label"] == 1].copy()
val_positive = val_pairs[val_pairs["label"] == 1].copy()

print("Positive training pairs:", len(train_positive))
print("Positive validation pairs:", len(val_positive))

Positive training pairs: 80004
Positive validation pairs: 9996

In [41]:
BATCH_SIZE = 128

train_job_idx = train_positive["job_idx"].values
train_candidate_idx = train_positive["candidate_idx"].values

val_job_idx = val_positive["job_idx"].values
val_candidate_idx = val_positive["candidate_idx"].values


def make_dataset(job_idx, candidate_idx, shuffle=True):
    job_vecs = job_embeddings[job_idx].astype("float32")
    candidate_vecs = candidate_embeddings[candidate_idx].astype("float32")

    dataset = tf.data.Dataset.from_tensor_slices(
        (job_vecs, candidate_vecs)
    )

    if shuffle:
        dataset = dataset.shuffle(
            buffer_size=len(job_vecs),
            reshuffle_each_iteration=True
        )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset


train_ds = make_dataset(
    train_job_idx,
    train_candidate_idx,
    shuffle=True
)

val_ds = make_dataset(
    val_job_idx,
    val_candidate_idx,
    shuffle=False
)

print("Datasets created successfully!")

Datasets created successfully!

In [43]:
def contrastive_loss(job_vectors, candidate_vectors):
    # Similarity matrix
    logits = tf.matmul(
        job_vectors,
        candidate_vectors,
        transpose_b=True
    )

    # Temperature
    temperature = tf.exp(model.log_temperature)
    logits = logits / temperature

    batch_size = tf.shape(logits)[0]

    labels = tf.range(batch_size)

    # Job -> Candidate
    loss_job_to_candidate = tf.keras.losses.sparse_categorical_crossentropy(
        labels,
        logits,
        from_logits=True
    )

    # Candidate -> Job
    loss_candidate_to_job = tf.keras.losses.sparse_categorical_crossentropy(
        labels,
        tf.transpose(logits),
        from_logits=True
    )

    return (
        tf.reduce_mean(loss_job_to_candidate) +
        tf.reduce_mean(loss_candidate_to_job)
    ) / 2

In [44]:
optimizer = keras.optimizers.Adam(
    learning_rate=1e-4
)

print("Optimizer ready!")

Optimizer ready!

In [45]:
@tf.function
def train_step(job_batch, candidate_batch):

    with tf.GradientTape() as tape:

        job_vectors = model.job_tower(job_batch)
        candidate_vectors = model.candidate_tower(candidate_batch)

        loss = contrastive_loss(
            job_vectors,
            candidate_vectors
        )

    gradients = tape.gradient(
        loss,
        model.trainable_variables
    )

    optimizer.apply_gradients(
        zip(gradients, model.trainable_variables)
    )

    return loss

In [46]:
for job_batch, candidate_batch in train_ds.take(1):

    loss = train_step(
        job_batch,
        candidate_batch
    )

    print("First batch loss:", float(loss))

First batch loss: 4.9664106369018555

In [47]:
EPOCHS = 10

for epoch in range(EPOCHS):

    train_losses = []

    for job_batch, candidate_batch in train_ds:

        loss = train_step(
            job_batch,
            candidate_batch
        )

        train_losses.append(float(loss))

    avg_train_loss = np.mean(train_losses)

    print(
        f"Epoch {epoch + 1}/{EPOCHS} "
        f"- Train Loss: {avg_train_loss:.4f}"
    )

Epoch 1/10 - Train Loss: 3.5676
Epoch 2/10 - Train Loss: 3.2350
Epoch 3/10 - Train Loss: 3.1107
Epoch 4/10 - Train Loss: 3.0113
Epoch 5/10 - Train Loss: 2.9175
Epoch 6/10 - Train Loss: 2.8257
Epoch 7/10 - Train Loss: 2.7317
Epoch 8/10 - Train Loss: 2.6321
Epoch 9/10 - Train Loss: 2.5331
Epoch 10/10 - Train Loss: 2.4333

In [48]:
def get_tower_embeddings(dataset):
    job_vectors = []
    candidate_vectors = []

    for job_batch, candidate_batch in dataset:
        job_vectors.append(
            model.job_tower(job_batch, training=False).numpy()
        )
        candidate_vectors.append(
            model.candidate_tower(candidate_batch, training=False).numpy()
        )

    return (
        np.vstack(job_vectors),
        np.vstack(candidate_vectors)
    )


val_job_vectors, val_candidate_vectors = get_tower_embeddings(val_ds)

print("Validation job vectors:", val_job_vectors.shape)
print("Validation candidate vectors:", val_candidate_vectors.shape)

Validation job vectors: (9996, 256)
Validation candidate vectors: (9996, 256)

In [49]:
def evaluate_retrieval(job_vectors, candidate_vectors, k_values=[1, 5, 10]):

    # Similarity matrix
    similarities = np.matmul(
        job_vectors,
        candidate_vectors.T
    )

    ranks = []

    for i in range(len(job_vectors)):

        ranking = np.argsort(
            -similarities[i]
        )

        # Correct candidate is at the same position
        correct_position = np.where(
            ranking == i
        )[0][0]

        ranks.append(correct_position + 1)

    ranks = np.array(ranks)

    results = {}

    for k in k_values:
        results[f"Recall@{k}"] = np.mean(ranks <= k)

    results["MRR"] = np.mean(1 / ranks)

    return results


results = evaluate_retrieval(
    val_job_vectors,
    val_candidate_vectors
)

results

{'Recall@1': np.float64(0.0020008003201280513),
 'Recall@5': np.float64(0.00820328131252501),
 'Recall@10': np.float64(0.01640656262505002),
 'MRR': np.float64(0.010538481198870393)}

In [50]:
def evaluate_real_retrieval(
    pairs,
    job_embeddings,
    candidate_embeddings,
    job_tower,
    candidate_tower,
    k_values=(1, 5, 10)
):
    # Unique jobs in validation set
    job_ids = pairs["job_idx"].unique()

    # Encode all candidates that appear in validation
    candidate_ids = pairs["candidate_idx"].unique()

    # Get embeddings
    job_input = job_embeddings[job_ids].astype("float32")
    candidate_input = candidate_embeddings[candidate_ids].astype("float32")

    # Two-Tower representations
    job_vectors = job_tower(
        job_input,
        training=False
    ).numpy()

    candidate_vectors = candidate_tower(
        candidate_input,
        training=False
    ).numpy()

    # Similarity matrix
    similarity = np.matmul(
        job_vectors,
        candidate_vectors.T
    )

    # candidate index -> position in matrix
    candidate_position = {
        cid: i
        for i, cid in enumerate(candidate_ids)
    }

    # Actual positive candidates for every job
    positive_pairs = pairs[pairs["label"] == 1]

    positives_by_job = (
        positive_pairs
        .groupby("job_idx")["candidate_idx"]
        .apply(set)
        .to_dict()
    )

    recalls = {k: [] for k in k_values}
    reciprocal_ranks = []

    for row_idx, job_id in enumerate(job_ids):

        if job_id not in positives_by_job:
            continue

        positive_candidates = positives_by_job[job_id]

        ranking = np.argsort(
            -similarity[row_idx]
        )

        ranked_candidate_ids = [
            candidate_ids[i]
            for i in ranking
        ]

        # Positions of all relevant candidates
        positive_ranks = [
            rank + 1
            for rank, candidate_id
            in enumerate(ranked_candidate_ids)
            if candidate_id in positive_candidates
        ]

        if not positive_ranks:
            continue

        best_rank = min(positive_ranks)

        for k in k_values:
            recalls[k].append(
                1 if best_rank <= k else 0
            )

        reciprocal_ranks.append(
            1 / best_rank
        )

    results = {}

    for k in k_values:
        results[f"Recall@{k}"] = np.mean(
            recalls[k]
        )

    results["MRR"] = np.mean(
        reciprocal_ranks
    )

    return results

In [51]:
real_results = evaluate_real_retrieval(
    val_pairs,
    job_embeddings,
    candidate_embeddings,
    model.job_tower,
    model.candidate_tower
)

real_results

{'Recall@1': np.float64(0.0021008403361344537),
 'Recall@5': np.float64(0.014105642256902761),
 'Recall@10': np.float64(0.023709483793517408),
 'MRR': np.float64(0.015254120517218667)}

In [52]:
def evaluate_use_baseline(pairs, job_embeddings, candidate_embeddings, k_values=(1, 5, 10)):

    job_ids = pairs["job_idx"].unique()
    candidate_ids = pairs["candidate_idx"].unique()

    job_vectors = job_embeddings[job_ids]
    candidate_vectors = candidate_embeddings[candidate_ids]

    similarity = np.matmul(
        job_vectors,
        candidate_vectors.T
    )

    positive_pairs = pairs[pairs["label"] == 1]

    positives_by_job = (
        positive_pairs
        .groupby("job_idx")["candidate_idx"]
        .apply(set)
        .to_dict()
    )

    recalls = {k: [] for k in k_values}
    reciprocal_ranks = []

    for row_idx, job_id in enumerate(job_ids):

        if job_id not in positives_by_job:
            continue

        positive_candidates = positives_by_job[job_id]

        ranking = np.argsort(
            -similarity[row_idx]
        )

        ranked_candidate_ids = [
            candidate_ids[i]
            for i in ranking
        ]

        positive_ranks = [
            rank + 1
            for rank, candidate_id in enumerate(ranked_candidate_ids)
            if candidate_id in positive_candidates
        ]

        if not positive_ranks:
            continue

        best_rank = min(positive_ranks)

        for k in k_values:
            recalls[k].append(
                int(best_rank <= k)
            )

        reciprocal_ranks.append(1 / best_rank)

    return {
        **{
            f"Recall@{k}": np.mean(recalls[k])
            for k in k_values
        },
        "MRR": np.mean(reciprocal_ranks)
    }

In [53]:
use_results = evaluate_use_baseline(
    val_pairs,
    job_embeddings,
    candidate_embeddings
)

use_results

{'Recall@1': np.float64(0.0027010804321728693),
 'Recall@5': np.float64(0.01050420168067227),
 'Recall@10': np.float64(0.018907563025210083),
 'MRR': np.float64(0.011724456283133244)}

In [54]:
import pandas as pd
import numpy as np
import re

jobs = pd.read_csv("data/jobs.csv")
candidates = pd.read_csv("data/candidates.csv")

train_pairs = pd.read_csv("data/train_pairs.csv")
val_pairs = pd.read_csv("data/val_pairs.csv")
test_pairs = pd.read_csv("data/test_pairs.csv")

job_embeddings = np.load("data/job_embeddings.npy")
candidate_embeddings = np.load("data/candidate_embeddings.npy")

print("Jobs:", jobs.shape)
print("Candidates:", candidates.shape)
print("Train pairs:", train_pairs.shape)
print("Job embeddings:", job_embeddings.shape)
print("Candidate embeddings:", candidate_embeddings.shape)

Jobs: (141897, 10)
Candidates: (210250, 11)
Train pairs: (160005, 3)
Job embeddings: (141897, 512)
Candidate embeddings: (210250, 512)

In [55]:
TECH_SKILLS = [
    "python", "java", "javascript", "typescript", "c++", "c#",
    "sql", "mysql", "postgresql", "mongodb",
    "machine learning", "deep learning", "artificial intelligence",
    "tensorflow", "pytorch", "scikit learn",
    "pandas", "numpy", "opencv",
    "nlp", "computer vision",
    "aws", "azure", "gcp",
    "docker", "kubernetes",
    "git", "github",
    "fastapi", "django", "flask",
    "react", "node.js",
    "spark", "hadoop",
    "airflow", "mlflow",
    "langchain", "llm",
    "data science", "data analysis",
    "statistics",
    "devops", "linux",
    "android", "ios",
    "solidity", "blockchain"
]


def extract_skills(text):
    if pd.isna(text):
        return set()

    text = str(text).lower()

    found = set()

    for skill in TECH_SKILLS:
        pattern = r"(?<![a-z0-9])" + re.escape(skill) + r"(?![a-z0-9])"

        if re.search(pattern, text):
            found.add(skill)

    return found

In [56]:
def combine_job_text(row):
    parts = [
        row.get("Position", ""),
        row.get("Long Description", ""),
        row.get("Primary Keyword", ""),
        str(row.get("Exp Years", ""))
    ]

    return " ".join(
        str(x) for x in parts
        if pd.notna(x)
    )


def combine_candidate_text(row):
    parts = [
        row.get("Position", ""),
        row.get("Moreinfo", ""),
        row.get("Looking For", ""),
        row.get("Highlights", ""),
        row.get("Primary Keyword", ""),
        row.get("CV", ""),
        str(row.get("Experience Years", ""))
    ]

    return " ".join(
        str(x) for x in parts
        if pd.notna(x)
    )

In [57]:
jobs["combined_text"] = jobs.apply(
    combine_job_text,
    axis=1
)

candidates["combined_text"] = candidates.apply(
    combine_candidate_text,
    axis=1
)

In [58]:
jobs["skills"] = jobs["combined_text"].apply(
    extract_skills
)

candidates["skills"] = candidates["combined_text"].apply(
    extract_skills
)

In [59]:
print(jobs[["Position", "skills"]].head())
print(candidates[["Position", "skills"]].head())

                                            Position  \
0      10 + Blockchain Nodes / Masternodes to set up
1       10 .NET Developers (Middle and Senior level)
2  10X Engineer (co-founder, #4 employee, USD 11-...
3                          16 - Amazon Brand Manager
4                          16 - Amazon Brand Manager

                                              skills
0                                       {blockchain}
1                            {azure, react, c#, sql}
2  {c#, java, react, python, typescript, javascri...
3                                                 {}
4                                                 {}
                                            Position  \
0  13 years of exp || Solidity, C#, JavaScript ||...
1                                       1c Developer
2                                       1C developer
3                                       1C Developer
4                     #1 Customer Support Specialist

                                              skills
0  {solidity, c#, sql, github, react, mongodb, bl...
1                                                 {}
2                                                 {}
3               {docker, java, sql, postgresql, git}
4                                                 {}

In [60]:
def skill_similarity(job_skills, candidate_skills):

    if not job_skills:
        return 0.0

    if not candidate_skills:
        return 0.0

    intersection = len(
        job_skills & candidate_skills
    )

    union = len(
        job_skills | candidate_skills
    )

    return intersection / union if union else 0.0

In [61]:
from collections import defaultdict

# Candidate → skill set
candidate_skill_map = {
    idx: skills
    for idx, skills in enumerate(candidates["skills"])
}

job_skill_map = {
    idx: skills
    for idx, skills in enumerate(jobs["skills"])
}

In [62]:
skill_to_candidates = defaultdict(set)

for candidate_idx, skills in candidate_skill_map.items():

    for skill in skills:
        skill_to_candidates[skill].add(candidate_idx)

print("Skill index created:", len(skill_to_candidates))

Skill index created: 48

In [63]:
hard_negative_rows = []

positive_train = train_pairs[
    train_pairs["label"] == 1
]

for _, row in positive_train.iterrows():

    job_idx = int(row["job_idx"])
    positive_candidate = int(row["candidate_idx"])

    job_skills = job_skill_map.get(
        job_idx,
        set()
    )

    if not job_skills:
        continue

    # Candidates sharing at least one skill
    candidate_pool = set()

    for skill in job_skills:
        candidate_pool.update(
            skill_to_candidates.get(skill, set())
        )

    # Remove the positive candidate
    candidate_pool.discard(
        positive_candidate
    )

    scored_candidates = []

    for candidate_idx in candidate_pool:

        candidate_skills = candidate_skill_map.get(
            candidate_idx,
            set()
        )

        similarity = skill_similarity(
            job_skills,
            candidate_skills
        )

        # Keep plausible candidates
        if similarity > 0:
            scored_candidates.append(
                (candidate_idx, similarity)
            )

    # Highest-overlap candidates = hardest negatives
    scored_candidates.sort(
        key=lambda x: x[1],
        reverse=True
    )

    # Take up to 2 hard negatives
    for candidate_idx, similarity in scored_candidates[:2]:

        hard_negative_rows.append({
            "job_idx": job_idx,
            "candidate_idx": candidate_idx,
            "label": 0,
            "skill_similarity": similarity
        })

In [64]:
hard_negatives = pd.DataFrame(
    hard_negative_rows
)

print(
    "Hard negatives:",
    hard_negatives.shape
)

print(
    hard_negatives.head()
)

Hard negatives: (114528, 4)
   job_idx  candidate_idx  label  skill_similarity
0     8326         149830      0          0.833333
1     8326         158438      0          0.833333
2     5115           6954      0          1.000000
3     5115           9252      0          1.000000
4     6497         163884      0          1.000000

In [65]:
positive_lookup = set(
    zip(
        positive_train["job_idx"],
        positive_train["candidate_idx"]
    )
)

hard_negatives = hard_negatives[
    ~hard_negatives.apply(
        lambda r: (
            int(r["job_idx"]),
            int(r["candidate_idx"])
        ) in positive_lookup,
        axis=1
    )
]

print(
    "Clean hard negatives:",
    len(hard_negatives)
)

Clean hard negatives: 114502

In [66]:
positive_training = positive_train[
    ["job_idx", "candidate_idx"]
].copy()

positive_training["label"] = 1

hard_negatives = hard_negatives[
    ["job_idx", "candidate_idx"]
]

hard_negatives["label"] = 0

improved_pairs = pd.concat(
    [
        positive_training,
        hard_negatives
    ],
    ignore_index=True
)

print("Improved training dataset:")
print(improved_pairs.shape)

print(
    improved_pairs["label"].value_counts()
)

Improved training dataset:
(194506, 3)
label
0    114502
1     80004
Name: count, dtype: int64

In [67]:
# Separate positives and negatives
positive_pairs = improved_pairs[
    improved_pairs["label"] == 1
].copy()

negative_pairs = improved_pairs[
    improved_pairs["label"] == 0
].copy()

print("Positive pairs:", len(positive_pairs))
print("Negative pairs:", len(negative_pairs))

Positive pairs: 80004
Negative pairs: 114502

In [68]:
negative_by_job = (
    negative_pairs
    .groupby("job_idx")["candidate_idx"]
    .apply(list)
    .to_dict()
)

print("Jobs with negatives:", len(negative_by_job))

Jobs with negatives: 19088

In [69]:
training_triples = []

for _, row in positive_pairs.iterrows():

    job_idx = int(row["job_idx"])
    positive_candidate = int(row["candidate_idx"])

    negatives = negative_by_job.get(job_idx, [])

    if not negatives:
        continue

    for negative_candidate in negatives[:2]:

        training_triples.append({
            "job_idx": job_idx,
            "positive_candidate_idx": positive_candidate,
            "negative_candidate_idx": negative_candidate
        })

training_triples = pd.DataFrame(training_triples)

print("Training triples:", training_triples.shape)
print(training_triples.head())

Training triples: (114528, 3)
   job_idx  positive_candidate_idx  negative_candidate_idx
0     8326                  209786                  149830
1     8326                  209786                  158438
2     5115                  169819                    6954
3     5115                  169819                    9252
4     6497                  174113                  163884

In [70]:
job_train = job_embeddings[
    training_triples["job_idx"].values
].astype("float32")

positive_train = candidate_embeddings[
    training_triples["positive_candidate_idx"].values
].astype("float32")

negative_train = candidate_embeddings[
    training_triples["negative_candidate_idx"].values
].astype("float32")

print("Job:", job_train.shape)
print("Positive:", positive_train.shape)
print("Negative:", negative_train.shape)

Job: (114528, 512)
Positive: (114528, 512)
Negative: (114528, 512)

In [71]:
BATCH_SIZE = 256

train_dataset = tf.data.Dataset.from_tensor_slices(
    (
        job_train,
        positive_train,
        negative_train
    )
)

train_dataset = train_dataset.shuffle(
    buffer_size=len(job_train),
    reshuffle_each_iteration=True
)

train_dataset = train_dataset.batch(
    BATCH_SIZE
)

train_dataset = train_dataset.prefetch(
    tf.data.AUTOTUNE
)

print("Dataset ready!")

Dataset ready!

In [72]:
MARGIN = 0.2

def ranking_loss(
    positive_scores,
    negative_scores
):

    loss = tf.maximum(
        0.0,
        MARGIN - positive_scores + negative_scores
    )

    return tf.reduce_mean(loss)

In [73]:
optimizer = keras.optimizers.Adam(
    learning_rate=1e-4
)

In [74]:
@tf.function
def ranking_train_step(
    job_batch,
    positive_batch,
    negative_batch
):

    with tf.GradientTape() as tape:

        # Job representation
        job_vector = model.job_tower(
            job_batch,
            training=True
        )

        # Positive candidate representation
        positive_vector = model.candidate_tower(
            positive_batch,
            training=True
        )

        # Negative candidate representation
        negative_vector = model.candidate_tower(
            negative_batch,
            training=True
        )

        # Cosine similarity because vectors are normalized
        positive_score = tf.reduce_sum(
            job_vector * positive_vector,
            axis=1
        )

        negative_score = tf.reduce_sum(
            job_vector * negative_vector,
            axis=1
        )

        loss = ranking_loss(
            positive_score,
            negative_score
        )

    gradients = tape.gradient(
        loss,
        model.trainable_variables
    )

    optimizer.apply_gradients(
        zip(
            gradients,
            model.trainable_variables
        )
    )

    return loss

In [75]:
for job_batch, positive_batch, negative_batch in train_dataset.take(1):

    loss = ranking_train_step(
        job_batch,
        positive_batch,
        negative_batch
    )

    print(
        "First ranking batch loss:",
        float(loss)
    )

d:\rock-n-roll-discover-server\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py:862: UserWarning: Gradients do not exist for variables ['two_tower_model/log_temperature'] when minimizing the loss. If using `model.compile()`, did you forget to provide a `loss` argument?
  warnings.warn(

First ranking batch loss: 0.11922646313905716

In [76]:
EPOCHS = 10

for epoch in range(EPOCHS):

    losses = []

    for job_batch, positive_batch, negative_batch in train_dataset:

        loss = ranking_train_step(
            job_batch,
            positive_batch,
            negative_batch
        )

        losses.append(float(loss))

    avg_loss = np.mean(losses)

    print(
        f"Epoch {epoch + 1}/{EPOCHS} "
        f"- Ranking Loss: {avg_loss:.4f}"
    )

Epoch 1/10 - Ranking Loss: 0.0574
Epoch 2/10 - Ranking Loss: 0.0331
Epoch 3/10 - Ranking Loss: 0.0233
Epoch 4/10 - Ranking Loss: 0.0169
Epoch 5/10 - Ranking Loss: 0.0129
Epoch 6/10 - Ranking Loss: 0.0099
Epoch 7/10 - Ranking Loss: 0.0077
Epoch 8/10 - Ranking Loss: 0.0060
Epoch 9/10 - Ranking Loss: 0.0048
Epoch 10/10 - Ranking Loss: 0.0038

In [77]:
improved_results = evaluate_real_retrieval(
    val_pairs,
    job_embeddings,
    candidate_embeddings,
    model.job_tower,
    model.candidate_tower
)

improved_results

{'Recall@1': np.float64(0.000900360144057623),
 'Recall@5': np.float64(0.006602641056422569),
 'Recall@10': np.float64(0.013805522208883553),
 'MRR': np.float64(0.008017797406683664)}

In [88]:
import pandas as pd
import numpy as np
import re
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [89]:
def clean_text(x):
    if pd.isna(x):
        return ""
    
    x = str(x).lower()
    x = x.replace("&", " and ")
    x = re.sub(r"[^a-z0-9+#.\- ]", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

In [90]:
jobs = jobs.copy()
candidates = candidates.copy()

jobs["job_text"] = (
    jobs["Position"].fillna("").astype(str) + " " +
    jobs["Long Description"].fillna("").astype(str) + " " +
    jobs["Primary Keyword"].fillna("").astype(str) + " " +
    jobs["Exp Years"].fillna("").astype(str) + " " +
    jobs["English Level"].fillna("").astype(str)
).map(clean_text)

candidates["candidate_text"] = (
    candidates["Position"].fillna("").astype(str) + " " +
    candidates["Moreinfo"].fillna("").astype(str) + " " +
    candidates["Looking For"].fillna("").astype(str) + " " +
    candidates["Highlights"].fillna("").astype(str) + " " +
    candidates["Primary Keyword"].fillna("").astype(str) + " " +
    candidates["CV"].fillna("").astype(str) + " " +
    candidates["Experience Years"].fillna("").astype(str) + " " +
    candidates["English Level"].fillna("").astype(str)
).map(clean_text)

In [91]:
print(jobs[["Position", "job_text"]].head(2))
print(candidates[["Position", "candidate_text"]].head(2))

                                        Position  \
0  10 + Blockchain Nodes / Masternodes to set up
1   10 .NET Developers (Middle and Senior level)

                                            job_text
0  10 + blockchain nodes masternodes to set up re...
1  10 .net developers middle and senior level gre...
                                            Position  \
0  13 years of exp || Solidity, C#, JavaScript ||...
1                                       1c Developer

                                      candidate_text
0  13 years of exp solidity c# javascript cto vp ...
1  1c developer worked on a mobile application fo...

In [92]:
TECH_SKILLS = [
    "python", "java", "javascript", "typescript",
    "c++", "c#", "sql", "mysql", "postgresql", "mongodb",
    "machine learning", "deep learning", "artificial intelligence",
    "tensorflow", "pytorch", "scikit learn",
    "pandas", "numpy", "opencv", "nlp", "computer vision",
    "aws", "azure", "gcp",
    "docker", "kubernetes",
    "git", "github",
    "fastapi", "django", "flask",
    "react", "node.js",
    "spark", "hadoop", "airflow", "mlflow",
    "langchain", "llm",
    "data science", "data analysis", "statistics",
    "devops", "linux",
    "android", "ios",
    "solidity", "blockchain"
]

TECH_SKILLS = sorted(TECH_SKILLS, key=len, reverse=True)

In [93]:
def extract_skills(text):
    text = clean_text(text)
    found = set()

    for skill in TECH_SKILLS:
        pattern = r"(?<!\w)" + re.escape(skill) + r"(?!\w)"
        if re.search(pattern, text):
            found.add(skill)

    return found

In [ ]:
jobs["skills"] = jobs["job_text"].apply(extract_skills)
candidates["skills"] = candidates["candidate_text"].apply(extract_skills)

In [ ]:
print(jobs[["Position", "skills"]].head(10))
print(candidates[["Position", "skills"]].head(10))

In [ ]:
def parse_years(value):
    if pd.isna(value):
        return np.nan

    text = str(value).lower()

    # Examples: 3, 3.5, "3 years", "2-4"
    nums = re.findall(r"\d+(?:\.\d+)?", text)

    if not nums:
        return np.nan

    nums = [float(x) for x in nums]

    if len(nums) >= 2:
        return sum(nums[:2]) / 2

    return nums[0]

In [ ]:
jobs["experience"] = jobs["Exp Years"].apply(parse_years)
candidates["experience"] = candidates["Experience Years"].apply(parse_years)

In [ ]:
print(jobs["experience"].describe())
print(candidates["experience"].describe())

In [ ]:
candidate_skill_index = defaultdict(list)

for idx, skills in enumerate(candidates["skills"]):
    for skill in skills:
        candidate_skill_index[skill].append(idx)

In [ ]:
def get_candidate_pool(job_idx, max_pool=100):
    job_skills = jobs.iloc[job_idx]["skills"]

    pool = set()

    for skill in job_skills:
        for candidate_idx in candidate_skill_index.get(skill, []):
            pool.add(candidate_idx)

            if len(pool) >= max_pool:
                return list(pool)

    return list(pool)

In [ ]:
def skill_score(job_skills, candidate_skills):
    if not job_skills:
        return 0.0

    if not candidate_skills:
        return 0.0

    overlap = len(job_skills & candidate_skills)

    return overlap / len(job_skills)

In [ ]:
print(
    skill_score(
        {"python", "pytorch", "machine learning"},
        {"python", "pytorch", "sql"}
    )
)

In [ ]:
def experience_score(job_exp, candidate_exp):
    if pd.isna(job_exp) or pd.isna(candidate_exp):
        return 0.5

    difference = abs(job_exp - candidate_exp)

    if difference <= 0.5:
        return 1.0
    elif difference <= 1:
        return 0.9
    elif difference <= 2:
        return 0.7
    elif difference <= 3:
        return 0.4
    else:
        return 0.1

In [ ]:
all_positions = pd.concat([
    jobs["Position"],
    candidates["Position"]
]).fillna("").astype(str)

position_vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=2
)

position_vectorizer.fit(all_positions)

In [ ]:
job_position_vectors = position_vectorizer.transform(
    jobs["Position"].fillna("").astype(str)
)

candidate_position_vectors = position_vectorizer.transform(
    candidates["Position"].fillna("").astype(str)
)

In [ ]:
def semantic_score(job_idx, candidate_idx):
    j = job_embeddings[job_idx]
    c = candidate_embeddings[candidate_idx]

    score = np.dot(j, c)

    return float(np.clip(score, 0, 1))

In [ ]:
def calculate_relevance(job_idx, candidate_idx):

    job = jobs.iloc[job_idx]
    candidate = candidates.iloc[candidate_idx]

    skill = skill_score(
        job["skills"],
        candidate["skills"]
    )

    experience = experience_score(
        job["experience"],
        candidate["experience"]
    )

    semantic = semantic_score(
        job_idx,
        candidate_idx
    )

    pos_similarity = cosine_similarity(
        job_position_vectors[job_idx],
        candidate_position_vectors[candidate_idx]
    )[0][0]

    score = (
        0.40 * skill +
        0.30 * semantic +
        0.20 * experience +
        0.10 * pos_similarity
    )

    return float(score)

In [ ]:
NUM_JOBS = 5000

In [ ]:
training_pairs = []

for job_idx in range(NUM_JOBS):

    pool = get_candidate_pool(job_idx, max_pool=100)

    if len(pool) < 3:
        continue

    scored = []

    for candidate_idx in pool:
        score = calculate_relevance(job_idx, candidate_idx)

        scored.append(
            (job_idx, candidate_idx, score)
        )

    scored.sort(key=lambda x: x[2], reverse=True)

    # Best candidate
    positive = scored[0]

    # Hard negative: reasonably good but not the best
    hard_negative = None

    for item in scored[1:]:
        if item[2] < positive[2] - 0.05:
            hard_negative = item
            break

    if hard_negative is None:
        continue

    training_pairs.append({
        "job_idx": positive[0],
        "positive_candidate_idx": positive[1],
        "positive_score": positive[2],
        "negative_candidate_idx": hard_negative[1],
        "negative_score": hard_negative[2]
    })

In [ ]:
ranking_df = pd.DataFrame(training_pairs)

print(ranking_df.shape)
print(ranking_df.head())

In [ ]:
print(
    ranking_df[
        ["positive_score", "negative_score"]
    ].describe()
)

In [ ]:
print(
    "Average positive:",
    ranking_df["positive_score"].mean()
)

print(
    "Average negative:",
    ranking_df["negative_score"].mean()
)

In [ ]:
ranking_df.to_csv(
    "data/improved_ranking_pairs.csv",
    index=False
)

print("Saved:", len(ranking_df), "training pairs")

In [ ]:
print(ranking_df.shape)

print(ranking_df["positive_score"].describe())

print(ranking_df["negative_score"].describe())

print(ranking_df.head(10))